[package]
name = "IWR_68xx_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
ctrlc = "3.4.5"
serial2 = "0.2.28"
plotters = "0.3.7"
serde = {version = "1.0.217", features = ["derive"]}
serde_json = "1.0.135"
tokio = {version="1.43.0", features=["sync"]}
